let heed = document.getElementById("heed")
let steam = document.getElementById("steam")
let reff = document.getElementById("reff")
let firr = document.getElementById("firr")
let malli = document.getElementById("malli")
let acti = document.getElementById("acti")
let apply = document.getElementById("apply")
let mag = document.getElementById("mag")
let meg = document.getElementById("meg")
let refff = document.getElementById("refff")
let magg = document.getElementById("magg")
let mag1 = document.getElementById("mag1")
let mag2 = document.getElementById("mag2")
let mag3 = document.getElementById("mag3")
let mag4 = document.getElementById("mag4")
heed.style.backgroundColor = "rgb(1, 1, 34)"
heed.style.justifyItems = "center"
heed.style.width = "100%"
heed.style.color = "white"
heed.style.backgroundSize = "cover"
steam.style.padding = "5%"
steam.style.fontSize = "50px"
steam.style.fontWeight = "500"
magg.style.borderRadius = "30px"
refff.style.color = "white"
refff.style.textDecoration = "none"
firr.style.display = "flex"
firr.style.width = "90%"
firr.style.padding = "5%"
firr.style.marginTop = "3%"
firr.style.marginBottom = "3%"
malli.style.margin = "5%"
malli.style.width = "70%"
acti.style.marginBottom = "5%"
apply.style.color = "black"
apply. style.textDecoration = "none"
apply.style.backgroundColor = "rgba(226, 225, 225, 0.637)"
apply.style.padding = "2%"
mag.style.display = "flex"
mag.style.justifyContent = "center"
meg.style.display = "flex"
meg.style.justifyContent = "center"
mag1.style.width = "40%"
mag2.style.width = "50%"
mag3.style.width = "50%"
mag4.style.width = "40%"
let imgg = document.getElementsByClassName("imgg")
for(i = 0; i < imgg.length; i++){
    imgg[i].style.padding = "1%"
    imgg[i].style.borderRadius = "25px"
}